name: tunezmusic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_svg:
  animated_text_kit: ^4.2.2
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.3
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.1.1
  equatable: ^2.0.5
  http: ^1.3.0
  flutter_dotenv: ^5.0.2
  marquee: ^2.2.3
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  dio: ^5.4.0
  cookie_jar: ^4.0.5
  dio_cookie_manager: ^3.1.0
  video_player: ^2.9.3
  chewie: ^1.10.0
  visibility_detector: ^0.4.0
  palette_generator: ^0.3.3
  just_audio: ^0.9.18
  just_audio_background: ^0.0.1-beta.15
  intl: ^0.18.0
  android_intent_plus: ^4.0.3
  connectivity_plus: ^6.1.3
  
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_sticky_header:

flutter_icons:
  android: true
  image_path: "assets/images/logo.png"
  background_color: "#000000"

flutter:
  uses-material-design: true

  assets:
  - assets/fonts/
  - assets/images/
  - assets/vectors/
  - .env
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 600
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400   
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
